# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.8.6
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
